### ISSUE TITLE
large section of text will be truncated

### ISSUE THREAD

**Issue by Joey-Lee** [sibahota059/SPHChatCollectionView#4]
When sending a large section of text, then the text will be truncated.
By the way, I like this ui style very much. :)

**Comment by sibahota059** [comment]
Hi , I have fixed that issue in my updated control (https://github.com/sibahota059/FlatChatBubble) for now, you can browse the code from there, later i will update that in this repo too :+1:

**Comment by Joey-Lee** [comment]
@sibahota059: Thank you very much.
